### ISSUE TITLE
android not working

### ISSUE THREAD

**Issue by phuocantd** [lepunk/react-native-nfc-demo#3]
when i try input text: "yup" then log to 4(resp) and read data then log "" (resp: [178, 0, 0, 0, 0, 0, 127, 7, 136, 64, 0, 0, 0, 0, 0, 0])
I hope you update for android

**Comment by vppnode** [comment]
Hi @phuocantd, I have this working on an old Android Samsung Galaxy I9505 Mini and an Iphone, with no issues. only for reading and writing to Mifare UltraLight Cards.
